/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_3d_biped_mpc_mc_body_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};
static const casadi_int casadi_s4[3] = {2, 1, 1};

/* full_3d_biped_mpc_mc_body_constr_h_fun:(i0[12],i1[10],i2[0],i3[13])->(o0[2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16;
  a00=arg[0]? arg[0][5] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[1]? arg[1][0] : 0;
  a06=(a04*a05);
  a02=sin(a02);
  a07=(a01*a02);
  a08=arg[0]? arg[0][3] : 0;
  a09=sin(a08);
  a10=(a07*a09);
  a00=sin(a00);
  a08=cos(a08);
  a11=(a00*a08);
  a10=(a10-a11);
  a11=arg[1]? arg[1][1] : 0;
  a12=(a10*a11);
  a06=(a06+a12);
  a07=(a07*a08);
  a12=(a00*a09);
  a07=(a07+a12);
  a12=arg[1]? arg[1][2] : 0;
  a13=(a07*a12);
  a06=(a06+a13);
  a06=casadi_sq(a06);
  a13=(a00*a03);
  a14=(a13*a05);
  a00=(a00*a02);
  a15=(a00*a09);
  a16=(a01*a08);
  a15=(a15+a16);
  a16=(a15*a11);
  a14=(a14+a16);
  a00=(a00*a08);
  a01=(a01*a09);
  a00=(a00-a01);
  a01=(a00*a12);
  a14=(a14+a01);
  a14=casadi_sq(a14);
  a06=(a06+a14);
  a14=5.9999999999999998e-01;
  a09=(a03*a09);
  a11=(a09*a11);
  a05=(a02*a05);
  a11=(a11-a05);
  a03=(a03*a08);
  a12=(a03*a12);
  a11=(a11+a12);
  a11=(a14*a11);
  a11=casadi_sq(a11);
  a06=(a06-a11);
  if (res[0]!=0) res[0][0]=a06;
  a06=arg[1]? arg[1][5] : 0;
  a04=(a04*a06);
  a11=arg[1]? arg[1][6] : 0;
  a10=(a10*a11);
  a04=(a04+a10);
  a10=arg[1]? arg[1][7] : 0;
  a07=(a07*a10);
  a04=(a04+a07);
  a04=casadi_sq(a04);
  a13=(a13*a06);
  a15=(a15*a11);
  a13=(a13+a15);
  a00=(a00*a10);
  a13=(a13+a00);
  a13=casadi_sq(a13);
  a04=(a04+a13);
  a09=(a09*a11);
  a02=(a02*a06);
  a09=(a09-a02);
  a03=(a03*a10);
  a09=(a09+a03);
  a14=(a14*a09);
  a14=casadi_sq(a14);
  a04=(a04-a14);
  if (res[0]!=0) res[0][1]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real full_3d_biped_mpc_mc_body_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
