/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {13, 1, 1};
static const casadi_int casadi_s4[3] = {2, 1, 1};
static const casadi_int casadi_s5[17] = 
  {22, 2, 0, 6, 12, 0, 1, 2,
  13, 14, 15, 5, 6, 7, 13, 14,
  15};
static const casadi_int casadi_s6[3] = {2, 0, 1};

/* full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt:(i0[12],i1[10],i2[0],i3[13])->(o0[2],o1[22x2,12nz],o2[2x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37;
  a00=arg[0]? arg[0][5] : 0;
  a01=cos(a00);
  a02=arg[0]? arg[0][4] : 0;
  a03=cos(a02);
  a04=(a01*a03);
  a05=arg[1]? arg[1][0] : 0;
  a06=(a04*a05);
  a02=sin(a02);
  a07=(a01*a02);
  a08=arg[0]? arg[0][3] : 0;
  a09=sin(a08);
  a10=(a07*a09);
  a00=sin(a00);
  a08=cos(a08);
  a11=(a00*a08);
  a10=(a10-a11);
  a11=arg[1]? arg[1][1] : 0;
  a12=(a10*a11);
  a06=(a06+a12);
  a12=(a07*a08);
  a13=(a00*a09);
  a12=(a12+a13);
  a13=arg[1]? arg[1][2] : 0;
  a14=(a12*a13);
  a06=(a06+a14);
  a14=casadi_sq(a06);
  a15=(a00*a03);
  a16=(a15*a05);
  a17=(a00*a02);
  a18=(a17*a09);
  a19=(a01*a08);
  a18=(a18+a19);
  a19=(a18*a11);
  a16=(a16+a19);
  a19=(a17*a08);
  a20=(a01*a09);
  a19=(a19-a20);
  a20=(a19*a13);
  a16=(a16+a20);
  a20=casadi_sq(a16);
  a14=(a14+a20);
  a20=5.9999999999999998e-01;
  a21=(a03*a09);
  a22=(a21*a11);
  a23=(a02*a05);
  a22=(a22-a23);
  a23=(a03*a08);
  a24=(a23*a13);
  a22=(a22+a24);
  a22=(a20*a22);
  a24=casadi_sq(a22);
  a14=(a14-a24);
  if (res[0]!=0) res[0][0]=a14;
  a14=arg[1]? arg[1][5] : 0;
  a24=(a04*a14);
  a25=arg[1]? arg[1][6] : 0;
  a26=(a10*a25);
  a24=(a24+a26);
  a26=arg[1]? arg[1][7] : 0;
  a27=(a12*a26);
  a24=(a24+a27);
  a27=casadi_sq(a24);
  a28=(a15*a14);
  a29=(a18*a25);
  a28=(a28+a29);
  a29=(a19*a26);
  a28=(a28+a29);
  a29=casadi_sq(a28);
  a27=(a27+a29);
  a29=(a21*a25);
  a30=(a02*a14);
  a29=(a29-a30);
  a30=(a23*a26);
  a29=(a29+a30);
  a29=(a20*a29);
  a30=casadi_sq(a29);
  a27=(a27-a30);
  if (res[0]!=0) res[0][1]=a27;
  a22=(a22+a22);
  a22=(a20*a22);
  a27=(a02*a22);
  a16=(a16+a16);
  a30=(a15*a16);
  a27=(a27+a30);
  a06=(a06+a06);
  a30=(a04*a06);
  a27=(a27+a30);
  if (res[1]!=0) res[1][0]=a27;
  a27=(a18*a16);
  a30=(a21*a22);
  a27=(a27-a30);
  a30=(a10*a06);
  a27=(a27+a30);
  if (res[1]!=0) res[1][1]=a27;
  a27=(a19*a16);
  a30=(a23*a22);
  a27=(a27-a30);
  a30=(a12*a06);
  a27=(a27+a30);
  if (res[1]!=0) res[1][2]=a27;
  a27=(a11*a16);
  a30=(a17*a27);
  a31=(a11*a22);
  a32=(a03*a31);
  a33=(a13*a16);
  a34=(a01*a33);
  a32=(a32+a34);
  a30=(a30-a32);
  a32=(a13*a06);
  a34=(a00*a32);
  a30=(a30+a34);
  a11=(a11*a06);
  a34=(a07*a11);
  a30=(a30+a34);
  a30=(a08*a30);
  a34=(a17*a33);
  a13=(a13*a22);
  a35=(a03*a13);
  a34=(a34-a35);
  a35=(a01*a27);
  a34=(a34+a35);
  a35=(a07*a32);
  a34=(a34+a35);
  a35=(a00*a11);
  a34=(a34-a35);
  a34=(a09*a34);
  a30=(a30-a34);
  if (res[1]!=0) res[1][3]=a30;
  a22=(a05*a22);
  a30=(a08*a33);
  a34=(a00*a30);
  a22=(a22+a34);
  a34=(a09*a27);
  a35=(a00*a34);
  a22=(a22+a35);
  a35=(a08*a32);
  a36=(a01*a35);
  a22=(a22+a36);
  a36=(a09*a11);
  a37=(a01*a36);
  a22=(a22+a37);
  a22=(a03*a22);
  a16=(a05*a16);
  a37=(a00*a16);
  a13=(a08*a13);
  a31=(a09*a31);
  a13=(a13+a31);
  a37=(a37-a13);
  a05=(a05*a06);
  a06=(a01*a05);
  a37=(a37+a06);
  a37=(a02*a37);
  a22=(a22-a37);
  if (res[1]!=0) res[1][4]=a22;
  a30=(a02*a30);
  a34=(a02*a34);
  a30=(a30+a34);
  a16=(a03*a16);
  a30=(a30+a16);
  a32=(a09*a32);
  a30=(a30+a32);
  a11=(a08*a11);
  a30=(a30-a11);
  a30=(a01*a30);
  a27=(a08*a27);
  a33=(a09*a33);
  a27=(a27-a33);
  a35=(a02*a35);
  a27=(a27+a35);
  a36=(a02*a36);
  a27=(a27+a36);
  a05=(a03*a05);
  a27=(a27+a05);
  a27=(a00*a27);
  a30=(a30-a27);
  if (res[1]!=0) res[1][5]=a30;
  a29=(a29+a29);
  a20=(a20*a29);
  a29=(a02*a20);
  a28=(a28+a28);
  a15=(a15*a28);
  a29=(a29+a15);
  a24=(a24+a24);
  a04=(a04*a24);
  a29=(a29+a04);
  if (res[1]!=0) res[1][6]=a29;
  a18=(a18*a28);
  a21=(a21*a20);
  a18=(a18-a21);
  a10=(a10*a24);
  a18=(a18+a10);
  if (res[1]!=0) res[1][7]=a18;
  a19=(a19*a28);
  a23=(a23*a20);
  a19=(a19-a23);
  a12=(a12*a24);
  a19=(a19+a12);
  if (res[1]!=0) res[1][8]=a19;
  a19=(a25*a28);
  a12=(a17*a19);
  a23=(a25*a20);
  a18=(a03*a23);
  a10=(a26*a28);
  a21=(a01*a10);
  a18=(a18+a21);
  a12=(a12-a18);
  a18=(a26*a24);
  a21=(a00*a18);
  a12=(a12+a21);
  a25=(a25*a24);
  a21=(a07*a25);
  a12=(a12+a21);
  a12=(a08*a12);
  a17=(a17*a10);
  a26=(a26*a20);
  a21=(a03*a26);
  a17=(a17-a21);
  a21=(a01*a19);
  a17=(a17+a21);
  a07=(a07*a18);
  a17=(a17+a07);
  a07=(a00*a25);
  a17=(a17-a07);
  a17=(a09*a17);
  a12=(a12-a17);
  if (res[1]!=0) res[1][9]=a12;
  a20=(a14*a20);
  a12=(a08*a10);
  a17=(a00*a12);
  a20=(a20+a17);
  a17=(a09*a19);
  a07=(a00*a17);
  a20=(a20+a07);
  a07=(a08*a18);
  a21=(a01*a07);
  a20=(a20+a21);
  a21=(a09*a25);
  a29=(a01*a21);
  a20=(a20+a29);
  a20=(a03*a20);
  a28=(a14*a28);
  a29=(a00*a28);
  a26=(a08*a26);
  a23=(a09*a23);
  a26=(a26+a23);
  a29=(a29-a26);
  a14=(a14*a24);
  a24=(a01*a14);
  a29=(a29+a24);
  a29=(a02*a29);
  a20=(a20-a29);
  if (res[1]!=0) res[1][10]=a20;
  a12=(a02*a12);
  a17=(a02*a17);
  a12=(a12+a17);
  a28=(a03*a28);
  a12=(a12+a28);
  a18=(a09*a18);
  a12=(a12+a18);
  a25=(a08*a25);
  a12=(a12-a25);
  a01=(a01*a12);
  a08=(a08*a19);
  a09=(a09*a10);
  a08=(a08-a09);
  a07=(a02*a07);
  a08=(a08+a07);
  a02=(a02*a21);
  a08=(a08+a02);
  a03=(a03*a14);
  a08=(a08+a03);
  a00=(a00*a08);
  a01=(a01-a00);
  if (res[1]!=0) res[1][11]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
