/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[46] = 
  {12, 12, 0, 0, 0, 0, 6, 12,
  15, 16, 17, 18, 21, 26, 31, 3,
  4, 5, 6, 7, 8, 3, 4, 5,
  6, 7, 8, 5, 6, 7, 0, 1,
  2, 3, 10, 11, 3, 4, 5, 9,
  11, 3, 4, 5, 9, 10};
static const casadi_int casadi_s6[27] = 
  {12, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s7[47] = 
  {12, 10, 0, 5, 10, 15, 16, 17,
  22, 27, 32, 33, 34, 6, 7, 8,
  10, 11, 6, 7, 8, 9, 11, 6,
  7, 8, 9, 10, 10, 9, 6, 7,
  8, 10, 11, 6, 7, 8, 9, 11,
  6, 7, 8, 9, 10, 10, 9};
static const casadi_int casadi_s8[3] = {12, 0, 1};

/* full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z:(i0[12],i1[12],i2[10],i3[0],i4[],i5[13])->(o0[12x12,31nz],o1[12x12,12nz],o2[12x10,34nz],o3[12x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34;
  a00=arg[0]? arg[0][3] : 0;
  a01=sin(a00);
  a02=arg[0]? arg[0][9] : 0;
  a03=arg[0]? arg[0][4] : 0;
  a04=cos(a03);
  a00=cos(a00);
  a05=(a04*a00);
  a06=(a02*a05);
  a06=(a01*a06);
  a03=sin(a03);
  a07=arg[0]? arg[0][10] : 0;
  a08=(a03*a07);
  a09=(a04*a01);
  a10=(a09*a02);
  a08=(a08+a10);
  a10=(a08*a00);
  a06=(a06+a10);
  a10=(a02*a09);
  a10=(a00*a10);
  a11=arg[0]? arg[0][11] : 0;
  a12=(a03*a11);
  a13=(a05*a02);
  a12=(a12+a13);
  a13=(a12*a01);
  a10=(a10+a13);
  a06=(a06-a10);
  a06=(a06/a04);
  a06=(-a06);
  if (res[0]!=0) res[0][0]=a06;
  a06=(a11*a05);
  a10=(a07*a09);
  a06=(a06+a10);
  a06=(a06/a04);
  if (res[0]!=0) res[0][1]=a06;
  a06=arg[0]? arg[0][5] : 0;
  a10=cos(a06);
  a06=sin(a06);
  a13=(a06*a03);
  a14=(a13*a00);
  a15=(a10*a01);
  a14=(a14-a15);
  a15=(a11*a14);
  a16=(a13*a01);
  a17=(a10*a00);
  a16=(a16+a17);
  a17=(a07*a16);
  a15=(a15+a17);
  a15=(a10*a15);
  a17=(a10*a03);
  a18=(a17*a00);
  a19=(a06*a01);
  a18=(a18+a19);
  a19=(a11*a18);
  a20=(a06*a00);
  a21=(a17*a01);
  a22=(a20-a21);
  a23=(a07*a22);
  a19=(a19-a23);
  a19=(a06*a19);
  a15=(a15-a19);
  a15=(a15/a04);
  a15=(-a15);
  if (res[0]!=0) res[0][2]=a15;
  a15=arg[2]? arg[2][1] : 0;
  a19=(a15*a18);
  a23=arg[2]? arg[2][2] : 0;
  a24=(a23*a22);
  a19=(a19+a24);
  a24=arg[2]? arg[2][6] : 0;
  a25=(a24*a18);
  a26=arg[2]? arg[2][7] : 0;
  a22=(a26*a22);
  a25=(a25+a22);
  a19=(a19+a25);
  a25=arg[5]? arg[5][0] : 0;
  a19=(a19/a25);
  a19=(-a19);
  if (res[0]!=0) res[0][3]=a19;
  a19=(a15*a14);
  a22=(a23*a16);
  a19=(a19-a22);
  a22=(a24*a14);
  a27=(a26*a16);
  a22=(a22-a27);
  a19=(a19+a22);
  a19=(a19/a25);
  a19=(-a19);
  if (res[0]!=0) res[0][4]=a19;
  a19=(a15*a05);
  a22=(a23*a09);
  a19=(a19-a22);
  a22=(a24*a05);
  a27=(a26*a09);
  a22=(a22-a27);
  a19=(a19+a22);
  a19=(a19/a25);
  a19=(-a19);
  if (res[0]!=0) res[0][5]=a19;
  a19=(a11*a04);
  a22=(a00*a03);
  a27=(a02*a22);
  a19=(a19-a27);
  a19=(a00*a19);
  a27=(a07*a04);
  a28=(a01*a03);
  a29=(a02*a28);
  a27=(a27-a29);
  a27=(a01*a27);
  a19=(a19+a27);
  a19=(a19/a04);
  a12=(a12*a00);
  a08=(a08*a01);
  a12=(a12+a08);
  a12=(a12/a04);
  a12=(a12/a04);
  a12=(a12*a03);
  a19=(a19+a12);
  a19=(-a19);
  if (res[0]!=0) res[0][6]=a19;
  a19=(a07*a22);
  a12=(a11*a28);
  a19=(a19-a12);
  a19=(a19/a04);
  a12=(a09*a11);
  a08=(a05*a07);
  a12=(a12-a08);
  a12=(a12/a04);
  a12=(a12/a04);
  a12=(a12*a03);
  a19=(a19+a12);
  if (res[0]!=0) res[0][7]=a19;
  a19=(a06*a04);
  a12=(a01*a19);
  a08=(a11*a12);
  a27=(a00*a19);
  a29=(a07*a27);
  a08=(a08-a29);
  a08=(a10*a08);
  a29=(a10*a04);
  a30=(a01*a29);
  a31=(a11*a30);
  a32=(a00*a29);
  a33=(a07*a32);
  a31=(a31-a33);
  a31=(a06*a31);
  a08=(a08-a31);
  a08=(a08/a04);
  a31=(a16*a11);
  a33=(a14*a07);
  a31=(a31-a33);
  a33=(a31*a10);
  a21=(a21-a20);
  a20=(a21*a11);
  a34=(a18*a07);
  a20=(a20-a34);
  a34=(a20*a06);
  a33=(a33-a34);
  a33=(a33/a04);
  a33=(a33/a04);
  a33=(a33*a03);
  a08=(a08+a33);
  a08=(-a08);
  if (res[0]!=0) res[0][8]=a08;
  a08=(a15*a30);
  a33=arg[2]? arg[2][0] : 0;
  a34=(a33*a17);
  a08=(a08-a34);
  a34=(a23*a32);
  a08=(a08+a34);
  a30=(a24*a30);
  a34=arg[2]? arg[2][5] : 0;
  a17=(a34*a17);
  a30=(a30-a17);
  a32=(a26*a32);
  a30=(a30+a32);
  a08=(a08+a30);
  a08=(a08/a25);
  a08=(-a08);
  if (res[0]!=0) res[0][9]=a08;
  a08=(a15*a12);
  a30=(a33*a13);
  a08=(a08-a30);
  a30=(a23*a27);
  a08=(a08+a30);
  a12=(a24*a12);
  a13=(a34*a13);
  a12=(a12-a13);
  a27=(a26*a27);
  a12=(a12+a27);
  a08=(a08+a12);
  a08=(a08/a25);
  a08=(-a08);
  if (res[0]!=0) res[0][10]=a08;
  a08=(a15*a28);
  a12=(a33*a04);
  a08=(a08+a12);
  a12=(a23*a22);
  a08=(a08+a12);
  a12=(a24*a28);
  a27=(a34*a04);
  a12=(a12+a27);
  a27=(a26*a22);
  a12=(a12+a27);
  a08=(a08+a12);
  a08=(a08/a25);
  if (res[0]!=0) res[0][11]=a08;
  a08=(a03*a10);
  a12=(a01*a08);
  a27=(a00*a06);
  a12=(a12-a27);
  a27=(a11*a12);
  a08=(a00*a08);
  a13=(a01*a06);
  a08=(a08+a13);
  a13=(a07*a08);
  a27=(a27-a13);
  a27=(a10*a27);
  a31=(a31*a06);
  a27=(a27-a31);
  a20=(a20*a10);
  a31=(a03*a06);
  a13=(a01*a31);
  a30=(a00*a10);
  a13=(a13+a30);
  a30=(a11*a13);
  a32=(a01*a10);
  a31=(a00*a31);
  a32=(a32-a31);
  a31=(a07*a32);
  a30=(a30+a31);
  a30=(a06*a30);
  a20=(a20-a30);
  a27=(a27-a20);
  a27=(a27/a04);
  a27=(-a27);
  if (res[0]!=0) res[0][12]=a27;
  a27=(a23*a32);
  a20=(a04*a06);
  a30=(a33*a20);
  a31=(a15*a13);
  a30=(a30+a31);
  a27=(a27-a30);
  a32=(a26*a32);
  a20=(a34*a20);
  a13=(a24*a13);
  a20=(a20+a13);
  a32=(a32-a20);
  a27=(a27+a32);
  a27=(a27/a25);
  a27=(-a27);
  if (res[0]!=0) res[0][13]=a27;
  a27=(a04*a10);
  a33=(a33*a27);
  a15=(a15*a12);
  a33=(a33+a15);
  a23=(a23*a08);
  a33=(a33+a23);
  a34=(a34*a27);
  a24=(a24*a12);
  a34=(a34+a24);
  a26=(a26*a08);
  a34=(a34+a26);
  a33=(a33+a34);
  a33=(a33/a25);
  a33=(-a33);
  if (res[0]!=0) res[0][14]=a33;
  a33=-1.;
  if (res[0]!=0) res[0][15]=a33;
  if (res[0]!=0) res[0][16]=a33;
  if (res[0]!=0) res[0][17]=a33;
  a33=(a00*a05);
  a34=(a01*a09);
  a33=(a33+a34);
  a33=(a33/a04);
  a33=(-a33);
  if (res[0]!=0) res[0][18]=a33;
  a33=arg[5]? arg[5][4] : 0;
  a34=arg[5]? arg[5][2] : 0;
  a26=(a33-a34);
  a08=(a26*a11);
  a24=arg[5]? arg[5][3] : 0;
  a08=(a08/a24);
  a08=(-a08);
  if (res[0]!=0) res[0][19]=a08;
  a08=(a34-a24);
  a12=(a07*a08);
  a12=(a12/a33);
  a12=(-a12);
  if (res[0]!=0) res[0][20]=a12;
  a28=(a28/a04);
  a28=(-a28);
  if (res[0]!=0) res[0][21]=a28;
  a00=(-a00);
  if (res[0]!=0) res[0][22]=a00;
  a00=(a06*a18);
  a28=(a10*a14);
  a00=(a00-a28);
  a00=(a00/a04);
  a00=(-a00);
  if (res[0]!=0) res[0][23]=a00;
  a00=(a24-a33);
  a11=(a11*a00);
  a11=(a11/a34);
  a11=(-a11);
  if (res[0]!=0) res[0][24]=a11;
  a08=(a08*a02);
  a08=(a08/a33);
  a08=(-a08);
  if (res[0]!=0) res[0][25]=a08;
  a22=(a22/a04);
  a22=(-a22);
  if (res[0]!=0) res[0][26]=a22;
  if (res[0]!=0) res[0][27]=a01;
  a10=(a10*a16);
  a06=(a06*a21);
  a10=(a10-a06);
  a10=(a10/a04);
  a10=(-a10);
  if (res[0]!=0) res[0][28]=a10;
  a00=(a00*a07);
  a00=(a00/a34);
  a00=(-a00);
  if (res[0]!=0) res[0][29]=a00;
  a02=(a02*a26);
  a02=(a02/a24);
  a02=(-a02);
  if (res[0]!=0) res[0][30]=a02;
  a02=1.;
  if (res[1]!=0) res[1][0]=a02;
  if (res[1]!=0) res[1][1]=a02;
  if (res[1]!=0) res[1][2]=a02;
  if (res[1]!=0) res[1][3]=a02;
  if (res[1]!=0) res[1][4]=a02;
  if (res[1]!=0) res[1][5]=a02;
  if (res[1]!=0) res[1][6]=a02;
  if (res[1]!=0) res[1][7]=a02;
  if (res[1]!=0) res[1][8]=a02;
  if (res[1]!=0) res[1][9]=a02;
  if (res[1]!=0) res[1][10]=a02;
  if (res[1]!=0) res[1][11]=a02;
  a29=(a29/a25);
  a29=(-a29);
  if (res[2]!=0) res[2][0]=a29;
  a19=(a19/a25);
  a19=(-a19);
  if (res[2]!=0) res[2][1]=a19;
  a03=(a03/a25);
  if (res[2]!=0) res[2][2]=a03;
  a02=arg[5]? arg[5][7] : 0;
  a26=(a02/a24);
  if (res[2]!=0) res[2][3]=a26;
  a26=arg[5]? arg[5][11] : 0;
  a26=(a26/a33);
  a26=(-a26);
  if (res[2]!=0) res[2][4]=a26;
  a21=(a21/a25);
  a21=(-a21);
  if (res[2]!=0) res[2][5]=a21;
  a16=(a16/a25);
  a16=(-a16);
  if (res[2]!=0) res[2][6]=a16;
  a09=(a09/a25);
  a09=(-a09);
  if (res[2]!=0) res[2][7]=a09;
  a02=(a02/a34);
  a02=(-a02);
  if (res[2]!=0) res[2][8]=a02;
  a02=arg[5]? arg[5][5] : 0;
  a26=(a02/a33);
  if (res[2]!=0) res[2][9]=a26;
  a18=(a18/a25);
  a18=(-a18);
  if (res[2]!=0) res[2][10]=a18;
  a14=(a14/a25);
  a14=(-a14);
  if (res[2]!=0) res[2][11]=a14;
  a05=(a05/a25);
  a05=(-a05);
  if (res[2]!=0) res[2][12]=a05;
  a25=arg[5]? arg[5][6] : 0;
  a25=(a25/a34);
  a25=(-a25);
  if (res[2]!=0) res[2][13]=a25;
  a02=(a02/a24);
  if (res[2]!=0) res[2][14]=a02;
  a02=(1./a24);
  a02=(-a02);
  if (res[2]!=0) res[2][15]=a02;
  a25=(1./a34);
  a25=(-a25);
  if (res[2]!=0) res[2][16]=a25;
  if (res[2]!=0) res[2][17]=a29;
  if (res[2]!=0) res[2][18]=a19;
  if (res[2]!=0) res[2][19]=a03;
  a03=arg[5]? arg[5][10] : 0;
  a19=(a03/a24);
  if (res[2]!=0) res[2][20]=a19;
  a19=arg[5]? arg[5][12] : 0;
  a19=(a19/a33);
  a19=(-a19);
  if (res[2]!=0) res[2][21]=a19;
  if (res[2]!=0) res[2][22]=a21;
  if (res[2]!=0) res[2][23]=a16;
  if (res[2]!=0) res[2][24]=a09;
  a03=(a03/a34);
  a03=(-a03);
  if (res[2]!=0) res[2][25]=a03;
  a03=arg[5]? arg[5][8] : 0;
  a33=(a03/a33);
  if (res[2]!=0) res[2][26]=a33;
  if (res[2]!=0) res[2][27]=a18;
  if (res[2]!=0) res[2][28]=a14;
  if (res[2]!=0) res[2][29]=a05;
  a05=arg[5]? arg[5][9] : 0;
  a05=(a05/a34);
  a05=(-a05);
  if (res[2]!=0) res[2][30]=a05;
  a03=(a03/a24);
  if (res[2]!=0) res[2][31]=a03;
  if (res[2]!=0) res[2][32]=a02;
  if (res[2]!=0) res[2][33]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
