/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {12, 1, 1};
static const casadi_int casadi_s1[3] = {10, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {13, 1, 1};
static const casadi_int casadi_s5[46] = 
  {12, 12, 0, 0, 0, 0, 6, 12,
  15, 16, 17, 18, 21, 26, 31, 3,
  4, 5, 6, 7, 8, 3, 4, 5,
  6, 7, 8, 5, 6, 7, 0, 1,
  2, 3, 10, 11, 3, 4, 5, 9,
  11, 3, 4, 5, 9, 10};
static const casadi_int casadi_s6[27] = 
  {12, 12, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 0,
  1, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s7[47] = 
  {12, 10, 0, 5, 10, 15, 16, 17,
  22, 27, 32, 33, 34, 6, 7, 8,
  10, 11, 6, 7, 8, 9, 11, 6,
  7, 8, 9, 10, 10, 9, 6, 7,
  8, 10, 11, 6, 7, 8, 9, 11,
  6, 7, 8, 9, 10, 10, 9};

/* full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u:(i0[12],i1[12],i2[10],i3[0],i4[],i5[13])->(o0[12],o1[12x12,31nz],o2[12x12,12nz],o3[12x10,34nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][6] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][7] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][8] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a02=sin(a01);
  a03=arg[0]? arg[0][11] : 0;
  a04=(a02*a03);
  a01=cos(a01);
  a05=arg[0]? arg[0][3] : 0;
  a06=cos(a05);
  a07=(a01*a06);
  a08=arg[0]? arg[0][9] : 0;
  a09=(a07*a08);
  a04=(a04+a09);
  a09=(a04*a06);
  a10=arg[0]? arg[0][10] : 0;
  a11=(a02*a10);
  a05=sin(a05);
  a12=(a01*a05);
  a13=(a12*a08);
  a11=(a11+a13);
  a13=(a11*a05);
  a09=(a09+a13);
  a09=(a09/a01);
  a00=(a00-a09);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a13=(a12*a03);
  a14=(a07*a10);
  a13=(a13-a14);
  a13=(a13/a01);
  a00=(a00+a13);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a14=arg[0]? arg[0][5] : 0;
  a15=sin(a14);
  a16=(a15*a02);
  a17=(a16*a05);
  a14=cos(a14);
  a18=(a14*a06);
  a17=(a17+a18);
  a18=(a17*a03);
  a19=(a16*a06);
  a20=(a14*a05);
  a19=(a19-a20);
  a20=(a19*a10);
  a18=(a18-a20);
  a20=(a18*a14);
  a21=(a14*a02);
  a22=(a21*a05);
  a23=(a15*a06);
  a24=(a22-a23);
  a25=(a24*a03);
  a26=(a21*a06);
  a27=(a15*a05);
  a26=(a26+a27);
  a27=(a26*a10);
  a25=(a25-a27);
  a27=(a25*a15);
  a20=(a20-a27);
  a20=(a20/a01);
  a00=(a00-a20);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a27=(a14*a01);
  a28=arg[2]? arg[2][0] : 0;
  a29=(a27*a28);
  a30=arg[2]? arg[2][1] : 0;
  a31=(a24*a30);
  a29=(a29+a31);
  a31=arg[2]? arg[2][2] : 0;
  a32=(a26*a31);
  a29=(a29+a32);
  a32=arg[2]? arg[2][5] : 0;
  a33=(a27*a32);
  a34=arg[2]? arg[2][6] : 0;
  a35=(a24*a34);
  a33=(a33+a35);
  a35=arg[2]? arg[2][7] : 0;
  a36=(a26*a35);
  a33=(a33+a36);
  a29=(a29+a33);
  a33=arg[5]? arg[5][0] : 0;
  a29=(a29/a33);
  a00=(a00-a29);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a29=(a15*a01);
  a36=(a29*a28);
  a37=(a17*a30);
  a36=(a36+a37);
  a37=(a19*a31);
  a36=(a36+a37);
  a37=(a29*a32);
  a38=(a17*a34);
  a37=(a37+a38);
  a38=(a19*a35);
  a37=(a37+a38);
  a36=(a36+a37);
  a36=(a36/a33);
  a00=(a00-a36);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a36=(a12*a30);
  a37=(a02*a28);
  a36=(a36-a37);
  a37=(a07*a31);
  a36=(a36+a37);
  a37=(a12*a34);
  a38=(a02*a32);
  a37=(a37-a38);
  a38=(a07*a35);
  a37=(a37+a38);
  a36=(a36+a37);
  a36=(a36/a33);
  a37=arg[5]? arg[5][1] : 0;
  a36=(a36-a37);
  a00=(a00-a36);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a36=arg[5]? arg[5][6] : 0;
  a37=(a36*a31);
  a38=arg[5]? arg[5][7] : 0;
  a39=(a38*a30);
  a37=(a37+a39);
  a39=arg[2]? arg[2][4] : 0;
  a37=(a37+a39);
  a39=arg[5]? arg[5][9] : 0;
  a40=(a39*a35);
  a41=arg[5]? arg[5][10] : 0;
  a42=(a41*a34);
  a40=(a40+a42);
  a42=arg[2]? arg[2][9] : 0;
  a40=(a40+a42);
  a37=(a37+a40);
  a40=arg[5]? arg[5][3] : 0;
  a42=arg[5]? arg[5][4] : 0;
  a43=(a40-a42);
  a44=(a43*a10);
  a45=(a44*a03);
  a37=(a37+a45);
  a45=arg[5]? arg[5][2] : 0;
  a37=(a37/a45);
  a00=(a00-a37);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a37=arg[2]? arg[2][3] : 0;
  a46=(a38*a28);
  a47=arg[5]? arg[5][5] : 0;
  a48=(a47*a31);
  a46=(a46+a48);
  a37=(a37-a46);
  a46=arg[2]? arg[2][8] : 0;
  a48=(a41*a32);
  a49=arg[5]? arg[5][8] : 0;
  a50=(a49*a35);
  a48=(a48+a50);
  a46=(a46-a48);
  a37=(a37+a46);
  a46=(a42-a45);
  a48=(a46*a03);
  a50=(a48*a08);
  a37=(a37+a50);
  a37=(a37/a40);
  a00=(a00-a37);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a37=arg[5]? arg[5][11] : 0;
  a50=(a37*a28);
  a51=(a47*a30);
  a50=(a50-a51);
  a51=arg[5]? arg[5][12] : 0;
  a52=(a51*a32);
  a53=(a49*a34);
  a52=(a52-a53);
  a50=(a50+a52);
  a52=(a45-a40);
  a53=(a52*a08);
  a54=(a53*a10);
  a50=(a50+a54);
  a50=(a50/a42);
  a00=(a00-a50);
  if (res[0]!=0) res[0][11]=a00;
  a00=(a08*a07);
  a00=(a05*a00);
  a11=(a11*a06);
  a00=(a00+a11);
  a11=(a08*a12);
  a11=(a06*a11);
  a04=(a04*a05);
  a11=(a11+a04);
  a00=(a00-a11);
  a00=(a00/a01);
  a00=(-a00);
  if (res[1]!=0) res[1][0]=a00;
  a00=(a03*a07);
  a11=(a10*a12);
  a00=(a00+a11);
  a00=(a00/a01);
  if (res[1]!=0) res[1][1]=a00;
  a00=(a03*a19);
  a11=(a10*a17);
  a00=(a00+a11);
  a00=(a14*a00);
  a11=(a03*a26);
  a23=(a23-a22);
  a22=(a10*a23);
  a11=(a11-a22);
  a11=(a15*a11);
  a00=(a00-a11);
  a00=(a00/a01);
  a00=(-a00);
  if (res[1]!=0) res[1][2]=a00;
  a00=(a30*a26);
  a11=(a31*a23);
  a00=(a00+a11);
  a11=(a34*a26);
  a23=(a35*a23);
  a11=(a11+a23);
  a00=(a00+a11);
  a00=(a00/a33);
  a00=(-a00);
  if (res[1]!=0) res[1][3]=a00;
  a00=(a30*a19);
  a11=(a31*a17);
  a00=(a00-a11);
  a11=(a34*a19);
  a23=(a35*a17);
  a11=(a11-a23);
  a00=(a00+a11);
  a00=(a00/a33);
  a00=(-a00);
  if (res[1]!=0) res[1][4]=a00;
  a00=(a30*a07);
  a11=(a31*a12);
  a00=(a00-a11);
  a11=(a34*a07);
  a23=(a35*a12);
  a11=(a11-a23);
  a00=(a00+a11);
  a00=(a00/a33);
  a00=(-a00);
  if (res[1]!=0) res[1][5]=a00;
  a00=(a03*a01);
  a11=(a06*a02);
  a23=(a08*a11);
  a00=(a00-a23);
  a00=(a06*a00);
  a23=(a10*a01);
  a22=(a05*a02);
  a04=(a08*a22);
  a23=(a23-a04);
  a23=(a05*a23);
  a00=(a00+a23);
  a00=(a00/a01);
  a09=(a09/a01);
  a09=(a09*a02);
  a00=(a00+a09);
  a00=(-a00);
  if (res[1]!=0) res[1][6]=a00;
  a00=(a10*a11);
  a09=(a03*a22);
  a00=(a00-a09);
  a00=(a00/a01);
  a13=(a13/a01);
  a13=(a13*a02);
  a00=(a00+a13);
  if (res[1]!=0) res[1][7]=a00;
  a00=(a05*a29);
  a13=(a03*a00);
  a09=(a06*a29);
  a23=(a10*a09);
  a13=(a13-a23);
  a13=(a14*a13);
  a23=(a05*a27);
  a04=(a03*a23);
  a50=(a06*a27);
  a54=(a10*a50);
  a04=(a04-a54);
  a04=(a15*a04);
  a13=(a13-a04);
  a13=(a13/a01);
  a20=(a20/a01);
  a20=(a20*a02);
  a13=(a13+a20);
  a13=(-a13);
  if (res[1]!=0) res[1][8]=a13;
  a13=(a30*a23);
  a20=(a28*a21);
  a13=(a13-a20);
  a20=(a31*a50);
  a13=(a13+a20);
  a23=(a34*a23);
  a21=(a32*a21);
  a23=(a23-a21);
  a50=(a35*a50);
  a23=(a23+a50);
  a13=(a13+a23);
  a13=(a13/a33);
  a13=(-a13);
  if (res[1]!=0) res[1][9]=a13;
  a13=(a30*a00);
  a23=(a28*a16);
  a13=(a13-a23);
  a23=(a31*a09);
  a13=(a13+a23);
  a00=(a34*a00);
  a16=(a32*a16);
  a00=(a00-a16);
  a09=(a35*a09);
  a00=(a00+a09);
  a13=(a13+a00);
  a13=(a13/a33);
  a13=(-a13);
  if (res[1]!=0) res[1][10]=a13;
  a13=(a30*a22);
  a00=(a28*a01);
  a13=(a13+a00);
  a00=(a31*a11);
  a13=(a13+a00);
  a00=(a34*a22);
  a09=(a32*a01);
  a00=(a00+a09);
  a09=(a35*a11);
  a00=(a00+a09);
  a13=(a13+a00);
  a13=(a13/a33);
  if (res[1]!=0) res[1][11]=a13;
  a13=(a02*a14);
  a00=(a05*a13);
  a09=(a06*a15);
  a00=(a00-a09);
  a09=(a03*a00);
  a13=(a06*a13);
  a16=(a05*a15);
  a13=(a13+a16);
  a16=(a10*a13);
  a09=(a09-a16);
  a09=(a14*a09);
  a18=(a18*a15);
  a09=(a09-a18);
  a25=(a25*a14);
  a18=(a02*a15);
  a16=(a05*a18);
  a23=(a06*a14);
  a16=(a16+a23);
  a23=(a03*a16);
  a50=(a05*a14);
  a18=(a06*a18);
  a50=(a50-a18);
  a18=(a10*a50);
  a23=(a23+a18);
  a23=(a15*a23);
  a25=(a25-a23);
  a09=(a09-a25);
  a09=(a09/a01);
  a09=(-a09);
  if (res[1]!=0) res[1][12]=a09;
  a09=(a31*a50);
  a25=(a01*a15);
  a23=(a28*a25);
  a18=(a30*a16);
  a23=(a23+a18);
  a09=(a09-a23);
  a50=(a35*a50);
  a25=(a32*a25);
  a16=(a34*a16);
  a25=(a25+a16);
  a50=(a50-a25);
  a09=(a09+a50);
  a09=(a09/a33);
  a09=(-a09);
  if (res[1]!=0) res[1][13]=a09;
  a09=(a01*a14);
  a28=(a28*a09);
  a30=(a30*a00);
  a28=(a28+a30);
  a31=(a31*a13);
  a28=(a28+a31);
  a32=(a32*a09);
  a34=(a34*a00);
  a32=(a32+a34);
  a35=(a35*a13);
  a32=(a32+a35);
  a28=(a28+a32);
  a28=(a28/a33);
  a28=(-a28);
  if (res[1]!=0) res[1][14]=a28;
  a28=-1.;
  if (res[1]!=0) res[1][15]=a28;
  if (res[1]!=0) res[1][16]=a28;
  if (res[1]!=0) res[1][17]=a28;
  a28=(a06*a07);
  a32=(a05*a12);
  a28=(a28+a32);
  a28=(a28/a01);
  a28=(-a28);
  if (res[1]!=0) res[1][18]=a28;
  a48=(a48/a40);
  a48=(-a48);
  if (res[1]!=0) res[1][19]=a48;
  a10=(a10*a52);
  a10=(a10/a42);
  a10=(-a10);
  if (res[1]!=0) res[1][20]=a10;
  a22=(a22/a01);
  a22=(-a22);
  if (res[1]!=0) res[1][21]=a22;
  a06=(-a06);
  if (res[1]!=0) res[1][22]=a06;
  a06=(a15*a26);
  a22=(a14*a19);
  a06=(a06-a22);
  a06=(a06/a01);
  a06=(-a06);
  if (res[1]!=0) res[1][23]=a06;
  a03=(a03*a43);
  a03=(a03/a45);
  a03=(-a03);
  if (res[1]!=0) res[1][24]=a03;
  a53=(a53/a42);
  a53=(-a53);
  if (res[1]!=0) res[1][25]=a53;
  a11=(a11/a01);
  a11=(-a11);
  if (res[1]!=0) res[1][26]=a11;
  if (res[1]!=0) res[1][27]=a05;
  a14=(a14*a17);
  a15=(a15*a24);
  a14=(a14-a15);
  a14=(a14/a01);
  a14=(-a14);
  if (res[1]!=0) res[1][28]=a14;
  a44=(a44/a45);
  a44=(-a44);
  if (res[1]!=0) res[1][29]=a44;
  a08=(a08*a46);
  a08=(a08/a40);
  a08=(-a08);
  if (res[1]!=0) res[1][30]=a08;
  a08=1.;
  if (res[2]!=0) res[2][0]=a08;
  if (res[2]!=0) res[2][1]=a08;
  if (res[2]!=0) res[2][2]=a08;
  if (res[2]!=0) res[2][3]=a08;
  if (res[2]!=0) res[2][4]=a08;
  if (res[2]!=0) res[2][5]=a08;
  if (res[2]!=0) res[2][6]=a08;
  if (res[2]!=0) res[2][7]=a08;
  if (res[2]!=0) res[2][8]=a08;
  if (res[2]!=0) res[2][9]=a08;
  if (res[2]!=0) res[2][10]=a08;
  if (res[2]!=0) res[2][11]=a08;
  a27=(a27/a33);
  a27=(-a27);
  if (res[3]!=0) res[3][0]=a27;
  a29=(a29/a33);
  a29=(-a29);
  if (res[3]!=0) res[3][1]=a29;
  a02=(a02/a33);
  if (res[3]!=0) res[3][2]=a02;
  a08=(a38/a40);
  if (res[3]!=0) res[3][3]=a08;
  a37=(a37/a42);
  a37=(-a37);
  if (res[3]!=0) res[3][4]=a37;
  a24=(a24/a33);
  a24=(-a24);
  if (res[3]!=0) res[3][5]=a24;
  a17=(a17/a33);
  a17=(-a17);
  if (res[3]!=0) res[3][6]=a17;
  a12=(a12/a33);
  a12=(-a12);
  if (res[3]!=0) res[3][7]=a12;
  a38=(a38/a45);
  a38=(-a38);
  if (res[3]!=0) res[3][8]=a38;
  a38=(a47/a42);
  if (res[3]!=0) res[3][9]=a38;
  a26=(a26/a33);
  a26=(-a26);
  if (res[3]!=0) res[3][10]=a26;
  a19=(a19/a33);
  a19=(-a19);
  if (res[3]!=0) res[3][11]=a19;
  a07=(a07/a33);
  a07=(-a07);
  if (res[3]!=0) res[3][12]=a07;
  a36=(a36/a45);
  a36=(-a36);
  if (res[3]!=0) res[3][13]=a36;
  a47=(a47/a40);
  if (res[3]!=0) res[3][14]=a47;
  a47=(1./a40);
  a47=(-a47);
  if (res[3]!=0) res[3][15]=a47;
  a36=(1./a45);
  a36=(-a36);
  if (res[3]!=0) res[3][16]=a36;
  if (res[3]!=0) res[3][17]=a27;
  if (res[3]!=0) res[3][18]=a29;
  if (res[3]!=0) res[3][19]=a02;
  a02=(a41/a40);
  if (res[3]!=0) res[3][20]=a02;
  a51=(a51/a42);
  a51=(-a51);
  if (res[3]!=0) res[3][21]=a51;
  if (res[3]!=0) res[3][22]=a24;
  if (res[3]!=0) res[3][23]=a17;
  if (res[3]!=0) res[3][24]=a12;
  a41=(a41/a45);
  a41=(-a41);
  if (res[3]!=0) res[3][25]=a41;
  a42=(a49/a42);
  if (res[3]!=0) res[3][26]=a42;
  if (res[3]!=0) res[3][27]=a26;
  if (res[3]!=0) res[3][28]=a19;
  if (res[3]!=0) res[3][29]=a07;
  a39=(a39/a45);
  a39=(-a39);
  if (res[3]!=0) res[3][30]=a39;
  a49=(a49/a40);
  if (res[3]!=0) res[3][31]=a49;
  if (res[3]!=0) res[3][32]=a47;
  if (res[3]!=0) res[3][33]=a36;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_release(int mem) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_incref(void) {
}

CASADI_SYMBOL_EXPORT void full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int full_3d_biped_mpc_mc_body_impl_dae_fun_jac_x_xdot_u_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
